import type { Metadata } from 'next'
import {
  ClerkProvider
} from '@clerk/nextjs'
import './globals.css'
import { Inter } from 'next/font/google'

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="ko">
        <head>
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          />
        </head>

        <body className='antialiased'>         
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
